name: Deploy FastApi App

on: 
  push: 
    branches:
      - master

env: 
  HEALTHCHECK_URL: http://127.0.0.1:5000

jobs:
  Deploying-FastAPI:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout the code base from github
        uses: actions/checkout@v5

      - name: Setup the runner
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Build a dedicate conda env.
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.12"
          # Optional: Automatically activate a custom environment
          activate-environment: fastapi
          # Optional: Use an environment.yml file from your repo
          environment-file: env.yml
          # Recommended: Use mamba for faster dependency resolution
          use-mamba: true

      - name: Run the main module to make the App available.
        shell: bash -l {0}  # Required to ensure the environment is activated
        run: |
          nohup python main.py &

  Health-Check:
    needs: Deploying-FastAPI:
      runs-on: ubuntu-latest
     
      steps:
        - name: Running Health Checks on the App
          run: |
            for i in {1..10}; do curl -s -o /dev/null -w "%{http_code}"  $HEALTHCHECK_URL | grep "200" && echo "Health check passed successfully" && exit 0|| echo "Waiting for service ...";
              sleep 5;
            done;
            echo "Health check failed ***" && exit 1
